answer/projectname/projectname/urls.py
from django.contrib import admin
from django.urls import path, include
import appname.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', appname.views.main, name='main'),
    path('create', appname.views.create, name='create'),
    path('update/<int:pk>', appname.views.update, name='update'),
    path('delete/<int:pk>', appname.views.delete, name='delete'),
    path('signin', appname.views.signin, name='signin'),
    path('signup', appname.views.signup, name='signup'),
    path('comment/<int:post_id>', appname.views.comment, name='comment'),
    path('hashtag/<str:hashtag_name>', appname.views.hashtag, name='hashtag'),
    path('like/<int:pk>', appname.views.like, name='like'),

    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

answer/projectname/appname/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.

class Post(models.Model):
    def __str__(self):
        return self.title

    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="writer", default="")

    hashtag_field = models.CharField(max_length=200, blank=True)
    hashtags = models.ManyToManyField('Hashtag', blank=True)

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="likes")

class Hashtag(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)

class Comment(models.Model):
    def __str__(self):
        return self.text

    c_writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="c_writer", default="")
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=50)

class CustomUser(AbstractUser):
    def __str__(self):
        return self.username

    nickname = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)

answer/projectname/appname/forms.py
from django import forms
from .models import Post, CustomUser, Comment, Hashtag

# from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'hashtag_field']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class SigninForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']

class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password', 'nickname', 'phone_number']

answer/projectname/appname/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, CustomUser, Hashtag
from .forms import PostForm, SigninForm, UserForm, CommentForm, HashtagForm

# from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.http import HttpResponse

# Create your views here.
def main(request):
    posts = Post.objects.all()
    signin_form = SigninForm()
    comment_form = CommentForm()
    return render(request, 'appname/main.html', {'posts': posts, 'signin_form': signin_form,
    'comment_form': comment_form})

def create(request):
    if not request.user.is_active:
        return HttpResponse("Can't wirte a post without Sign In")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user

            hashtag_field = form.cleaned_data['hashtag_field']
            str_hashtags = hashtag_field.split('#')
            list_hashtags = list()

            for hashtag in str_hashtags:
                # hashtag = hashtag.strip()
                if Hashtag.objects.filter(name=hashtag):
                    list_hashtags.append(Hashtag.objects.get(name=hashtag))
                else:
                    temp_hashtag = HashtagForm().save(commit=False)
                    temp_hashtag.name = hashtag

                    temp_hashtag.save()
                    list_hashtags.append(temp_hashtag)

            post.save()
            post.hashtags.add(*list_hashtags)
            # form.save_m2m()
            return redirect('main')
    else:
        form = PostForm()
        return render(request, 'appname/create.html', {'form': form})

def read(request):
    return redirect('main')

def update(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if not request.user.is_active:
        return HttpResponse("로그인 부터하셈ㅋㅋ")
    elif post.writer != request.user:
        return HttpResponse("자기가 쓴 글만 수정 할 수 있어용")

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('main')
    else:
        form = PostForm(instance=post)
        return render(request, 'appname/create.html', {'form': form})

def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if not request.user.is_active:
        return HttpResponse("로그인 부터하셈ㅋㅋ")
    elif post.writer != request.user:
        return HttpResponse("자기가 쓴 글만 삭제할 수 있어용")
             
    post.delete()
    return redirect('main')

def comment(request, post_id):
    if not request.user.is_active:
        return HttpResponse("로그인 부터하셈ㅋㅋ")

    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.c_writer = request.user
            comment.post_id = post
            comment.text = form.cleaned_data['text']
            comment.save()
            return redirect('main')

def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)

        if user is not None:
            login(request, user)
            return redirect('main')
        else:
            return HttpResponse("로그인 실패. 다시 시도해보세요 ㅋ")

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = CustomUser.objects.create_user(username=form.cleaned_data['username'],
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password'],
            nickname=form.cleaned_data['nickname'],
            phone_number=form.cleaned_data['phone_number'])
            login(request, new_user)
            return redirect('main')
    else:
        form = UserForm()
        return render(request, 'appname/signup.html', {'form': form})

def hashtag(request, hashtag_name):
    hashtag = get_object_or_404(Hashtag, name=hashtag_name)
    return render(request, 'appname/hashtag.html', {'hashtag': hashtag})

def like(request, pk):
    if not request.user.is_active:
        return HttpResponse("로그인 부터하셈ㅋㅋ")

    post = get_object_or_404(Post, pk=pk)
    user = request.user

    if post.likes.filter(id=user.id).exists():
        post.likes.remove(user)
    else:
        post.likes.add(user)

    return redirect('main')

answer/projectname/appname/templates/appname/base.html
<!doctype html>
{% load static %}

<html>

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>myinstagram</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'appname/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'appname/css/one-page-wonder.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">myinstagram</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/create">create</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">signout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">signup</a>
          </li>
          {% endif %}
          
        </ul>
      </div>
    </div>
  </nav>

{% block header %}
{% endblock %}

  

{% block content %}
{% endblock %}

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'appname/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'appname/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

answer/projectname/appname/templates/appname/create.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">myinstagram</h1>
      <h2 class="masthead-subheading mb-0">hello likelion 8th</h2>
      <a href="/create" class="btn btn-primary btn-xl rounded-pill mt-5">write a post</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="submit">
</form>

{% endblock %}

answer/projectname/appname/templates/appname/hashtag.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">{{ hashtag.name }}</h1>

      <a href="/create" class="btn btn-primary btn-xl rounded-pill mt-5">write a post</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block content %}
{% for post in hashtag.post_set.all %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          {% if post.image %}
          <img class="img-fluid rounded-circle" src="{{ post.image.url }}" alt="">
          {% endif %}
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">

        <div class="p-5">
          <h4 class="display-6">{{ post.writer }}</h4>
          <h2 class="display-4">{{post.title}}</h2>
          <p>{{post.content}}</p>

          <span>
          {% for hashtag in post.hashtags.all %}
            {{ hashtag.name }}
          {% endfor %}
          </<span>
          <br>

          <a href="{% url 'update' pk=post.pk %}"> 수정하기 </a>
          <a href="{% url 'delete' pk=post.pk %}"> 삭제하기 </a>
        </div>

        {% for comment in post.comments.all %}
          <p>{{ comment.c_writer }} : {{ comment.text }}</p>
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endfor %}

{% endblock %}

answer/projectname/appname/templates/appname/main.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">myinstagram</h1>

      {% if user.is_authenticated %}
      <h2 class="masthead-subheading mb-0">hello {{ user.username }}</h2>
      <a href="{% url 'logout' %}"> sign out</a>
      {% else %}
      <h2 class="masthead-subheading mb-0">hello likelion 8th</h2>

      <a href="{% url 'signup' %}">회원가입하기</a>

      <form method="POST" action="/signin">
        {% csrf_token %}
        {{ signin_form.as_p }}
        <input type="submit" value="submit">
      </form>

      {% endif %}

      <a href="/create" class="btn btn-primary btn-xl rounded-pill mt-5">write a post</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

{% endblock %}

{% block content %}
{% load static %}

{% for post in posts %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          {% if post.image %}
          <img class="img-fluid rounded-circle" src="{{ post.image.url }}" alt="">
          {% endif %}
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">

        <div class="p-5">
          <h4 class="display-6">{{ post.writer }}</h4>
          <h2 class="display-4">{{post.title}}</h2>
          <p>{{post.content}}</p>

          <span>
          {% for hashtag in post.hashtags.all %}
            <a href="/hashtag/{{ hashtag.name }}">{{ hashtag.name }}</a>
          {% endfor %}
          </<span>
          <br>

          <a href="{% url 'update' pk=post.pk %}"> 수정하기 </a>
          <a href="{% url 'delete' pk=post.pk %}"> 삭제하기 </a>
        </div>

        <p>좋아요 {{ post.likes.count }}개</p>

        <a href="{% url 'like' pk=post.pk %}">
        {% if user in post.likes.all %}
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
          </svg>
        {% else %}
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
        </svg>
        {% endif %}
        </a>

        <form method="POST" action='/comment/{{ post.id }}'>
          {% csrf_token %}
          {{ comment_form.as_p }}
          <input type="submit" value="submit">
        </form>

        {% for comment in post.comments.all %}
          <p>{{ comment.c_writer }} : {{ comment.text }}</p>
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endfor %}

{% endblock %}

answer/projectname/appname/templates/appname/signup.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">myinstagram</h1>

      <a href="/create" class="btn btn-primary btn-xl rounded-pill mt-5">write a post</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
  {{ form.as_table }}
  </table>
  <input type="submit" value="submit">
</form>
{% endblock %}

answer/projectname/appname/templates/appname/update.html
{% extends 'appname/base.html' %}

{% block header %}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">myinstagram</h1>
      <h2 class="masthead-subheading mb-0">hello likelion 8th</h2>
      <a href="/create" class="btn btn-primary btn-xl rounded-pill mt-5">write a post</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="submit">
</form>

{% endblock %}